create table if not exists public.blocked_periods (
  id bigint generated by default as identity primary key,
  start_date date not null,
  end_date date not null,
  status text not null default 'unavailable',
  created_at timestamptz not null default now(),
  constraint valid_period check (end_date >= start_date),
  constraint valid_availability_status check (status in ('unavailable', 'limited')),
  constraint no_overlapping_periods exclude using gist (
    daterange(start_date, end_date, '[]') with &&
  )
);

alter table public.blocked_periods
add column if not exists status text not null default 'unavailable';

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'valid_availability_status'
      and conrelid = 'public.blocked_periods'::regclass
  ) then
    alter table public.blocked_periods
    add constraint valid_availability_status
    check (status in ('unavailable', 'limited'));
  end if;
end $$;

alter table public.blocked_periods enable row level security;

revoke all on table public.blocked_periods from anon, authenticated;
grant select on table public.blocked_periods to anon, authenticated;
grant insert, update, delete on table public.blocked_periods to authenticated;
grant usage, select on sequence public.blocked_periods_id_seq to authenticated;

drop policy if exists "Iedereen leest beschikbaarheid" on public.blocked_periods;
create policy "Iedereen leest beschikbaarheid"
on public.blocked_periods for select
to anon, authenticated
using (true);

drop policy if exists "Alleen beheerder voegt blokkeringen toe" on public.blocked_periods;
create policy "Alleen beheerder voegt blokkeringen toe"
on public.blocked_periods for insert
to authenticated
with check ((auth.jwt() ->> 'email') = 'info@fhamazul.es');

drop policy if exists "Alleen beheerder wijzigt blokkeringen" on public.blocked_periods;
create policy "Alleen beheerder wijzigt blokkeringen"
on public.blocked_periods for update
to authenticated
using ((auth.jwt() ->> 'email') = 'info@fhamazul.es')
with check ((auth.jwt() ->> 'email') = 'info@fhamazul.es');

drop policy if exists "Alleen beheerder verwijdert blokkeringen" on public.blocked_periods;
create policy "Alleen beheerder verwijdert blokkeringen"
on public.blocked_periods for delete
to authenticated
using ((auth.jwt() ->> 'email') = 'info@fhamazul.es');
